name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
    call-reusable-workflow:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./CI-CD
        steps:
            - name: Call Reusable CI-CD Workflow
              uses: ./.github/workflows/CI-CD.yml
